- name: create etcd data dir
  file: path={{ etcd_dir }} state=directory owner=etcd

- name: prepare etcd config
  set_fact:
    etcd_cluster: "aws-etcd1=http://172.31.27.1:7001,aws-etcd2=http://172.31.27.2:7001,aws-etcd3=http://172.31.27.3:7001"

# now when etcd-cluster-resizing, all the nodes will cause template changed and restart etcd
# TODO(chenyunfei) check whether is adding new lain-node
- name: config etcd
  template: src=etcd.env.j2 dest={{ etcd_dir }}/env owner=etcd
  notify:
    - restart etcd

- name: config etcd service
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  notify:
    - reload systemd for etcd
    - restart etcd

- meta: flush_handlers
