- name: create etcd user
  user: name=etcd createhome=no

- name: install etcd
  yum: pkg=etcd-{{ etcd_ver }}

# begin to reset etcd
- include: etcd-reset.yaml

- name: ensure etcd service started
  service: name=etcd enabled=yes state=started

- name: wait for etcd to be healthy
  shell: etcdctl cluster-health | grep "cluster is healthy"
  register: health_result
  until: health_result|success
  retries: 5
  delay: 5
  changed_when: False

- name: wait for etcd is ready to write
  command: etcdctl set /lain/test test
  register: result
  until: result|success
  retries: 5
  delay: 5
  changed_when: False

- name: Ship etcdctl bash-completion script
  copy: src=etcdctl_comp dest=/usr/share/bash-completion/completions/etcdctl
